export const types = {
  SET_NUMBER_CELL: "SET_NUMBER_CELL",
  INIT_ARRAY: 'INIT_ARRAY',
  TICK: 'TICK',
  SWITCH_PIECE: "SWITCH_PIECE",
  JUMP_TO: 'JUMP_TO',
  SORT: 'SORT',
  HANDLE_CLICK: "HANDLE_CLICK"
}


